### ISSUE TITLE
support standardjs ?

### ISSUE THREAD

**Issue by mojoaxel** [Thomaash/vis-configs#1]
Shouln't we support something like https://standardjs.com/

**Comment by Thomaash** [comment]
@mojoaxel Sorry for the delay, I forgot to enable watching of this repository.

The problem with Standard is that is supports only ECMAScript, so we would end up with Standard for JS and something else or nothing for TS. There is a 3rd party package for this but I had some issues using that (like that is was not formatting types).

We can however mimic Standard if you want. The current Prettier configuration is not so different from it (I used to use Standard before I started with TypeScript so I set up Prettier in a similar way). In fact it should even be possible to just add Standard after Prettier to get Standard code style for ECMAScript and it should leave the parts of TS it doesn't understand with whatever Prettier did to it (I can test it if you want Standard).

**Comment by Thomaash** [comment]
Oh and Standard doesn't allow trailing commas which causes some minor issues in Git diff because when a new last item or last property is added the line above is also changed (a new comma has to be added). The way it is now the comma is already there so only the added line shows up in diff. Not a big deal but I personally like trailing commas.

**Comment by mojoaxel** [comment]
My opinions to code-styling:
- Code-Styling is very personal. There is often no right or wrong!
  (Except in indentation: There, only tabs are ok, of course! :wink:). 
- To prevent styling-wars a very common code-style without customizations should be used (e.g. standardjs, prettier ...)
- If a code-styling exist it should automatically be enforced (e.g. by a pre-commit hook or something like travis)
- A code style should be introduced by a robot-committer or during a massiv rewrite of the library. If not, a lot of code changes get attributed to one person which destroys statistics. A good time to introduce is code-style could be e.g. a rewrite from js to ts :-)

**Comment by Thomaash** [comment]
Playing around with Standard I'm against it. Prettier is very aggressive which leads to consistent code style, there is not much left to be argued about. Standard is very permissive and allows a lot of variation. The only thing that goes in favor of Standard is configuration as there is more to argue about when configuring Prettier. On the other hand we will set the configuration here and then it will be very difficult to change. Also against Standard is the fact that it has no native support for TypeScript (well it has native support for ignoring TypeScript, but that's not very helpful). We would need to get another rule set for this which in my opinion defeats the zero configuration advantage of Standard (I managed to produce syntax errors during reformatting with this approach).

# Original
```typescript
interface I{foo:number|{foo:number;bar:string,map:Record<number|string,boolean|number|string>

      

}}

function test    (p:I):I{;return p;}

test([{
  foo: 7,
},{
  foo:8
},
{
  foo:9
},{
  foo:10
}
,{
foo:11
}
]
    )
```

# Standard
No config apart from setting up TypeScript parser.
```typescript
interface I{foo:number|{foo:number;bar:string, map:Record<number|string, boolean|number|string>

}}

function test (p:I):I { ;return p }

test([{
  foo: 7
}, {
  foo: 8
},
{
  foo: 9
}, {
  foo: 10
},
{
  foo: 11
}
]
)
```

# Prettier
No config apart from setting up TypeScript parser.
```typescript
interface I {
  foo:
    | number
    | {
        foo: number;
        bar: string;
        map: Record<number | string, boolean | number | string>;
      };
}

function test(p: I): I {
  return p;
}

test([
  {
    foo: 7
  },
  {
    foo: 8
  },
  {
    foo: 9
  },
  {
    foo: 10
  },
  {
    foo: 11
  }
]);
```

# Standard with TypeScript
Copy pasted config from the usage section in their readme.
```typescript
interface I{foo: number|{foo: numberbar: stringmap: Record<number|string, boolean|number|string>

}}

function test (p: I): I { ;return p}

test([{
  foo: 7
}, {
  foo: 8
},
{
  foo: 9
}, {
  foo: 10
},
{
  foo: 11
}
]
)
```
Note: This is not valid TypeScript.

**Comment by Thomaash** [comment]
There is a robot commiter for Prettier https://www.prettierci.com/ . It opens reformatting pull requests. Therefore a person doesn't get attributed authorship of a lot of changes just for running `eslint --fix`.

**Comment by mojoaxel** [comment]
I think I could lern to life with Prettier but I thnik we should use 100% the default config to prevent discussions!

**Comment by mojoaxel** [comment]
> There is a robot commiter for Prettier https://www.prettierci.com/

Maybe we could start with in the vis-util repository?

**Comment by Thomaash** [comment]
We'll use PrettierCI and Prettier with default config.
